namespace Soenneker.OpenZl.Util;
/// <summary>Standard graph identifiers for the bundled OpenZL revision.</summary>
public enum OpenZlGraph : uint
{
    Store = 2,
    Fse = 3,
    Huffman = 4,
    HuffmanHuf0 = 5,
    HuffmanPivco = 6,
    Entropy = 7,
    Constant = 8,
    Zstd = 9,
    Bitpack = 10,
    Flatpack = 11,
    FieldLz = 12,
    CompressGeneric = 13,
    SelectGenericLzBackend = 14,
    SegmentNumeric = 15,
    SelectNumeric = 16,
    MlSelector = 17,
    Clustering = 18,
    TryParseInt = 19,
    SimpleDataDescriptionLanguage = 20,
    SimpleDataDescriptionLanguageV2 = 21,
    Lz4 = 22,
    PartitionBitpack = 23,
    SegmentNum8FromSerial = 24,
    SegmentNum16FromSerial = 25,
    SegmentNum32FromSerial = 26,
    SegmentNum64FromSerial = 27,
    Lz = 28,
    SegmentSerial = 29,
    TransformerNumeric = 30,
    BruteForce = 31,
}
