name: build-and-test

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PipelineEnvironment: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Restore tests
        run: dotnet restore test/Soenneker.OpenZl.Util.Tests/Soenneker.OpenZl.Util.Tests.csproj --verbosity minimal

      - name: Build tests
        run: dotnet build test/Soenneker.OpenZl.Util.Tests/Soenneker.OpenZl.Util.Tests.csproj --configuration Release --no-restore --verbosity minimal

      - name: Test
        run: dotnet test --project test/Soenneker.OpenZl.Util.Tests/Soenneker.OpenZl.Util.Tests.csproj --configuration Release --no-build --no-restore --verbosity minimal

      - name: Pack
        run: dotnet pack src/Soenneker.OpenZl.Util/Soenneker.OpenZl.Util.csproj --configuration Release --no-build --no-restore --output . --verbosity minimal
